name: CI

on: [ push ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.4, phpunit: 9 }
          - { php: 8.0, phpunit: 10 }
          - { php: 8.1, phpunit: 10 }
          - { php: 8.2, phpunit: 10 }
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
      - uses: actions/checkout@v3
      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.env.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.env.php }}-composer-
      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.env.php }}"
          command: update -o --no-interaction --no-suggest --prefer-dist
      - uses: php-actions/phpunit@v3
        with:
          php_version: "${{ matrix.env.php }}"
          version: "${{ matrix.env.phpunit }}"
          configuration: "phpunit.xml"
      - name: Run tests (Behat)
        run: vendor/bin/behat -fprogress --strict
