name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          coverage: "none"
          configuration: "phpunit.xml"
          php_version: "7.4"
          phpunit_version: "9.5"
          phpunit_args: "--coverage-clover=coverage.xml"