name: CI

on: [ push ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.4, version: 9 }
          - { php: 8.0, version: 9 }
          - { php: 8.1, version: 9 }
          - { php: 8.2, version: 10 }
    steps:
      - uses: actions/checkout@v3
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.env.php }}"
      - uses: php-actions/phpunit@v3
        with:
          php_version: "${{ matrix.env.php }}"
          version: "${{ matrix.env.version }}"
          configuration: "phpunit.xml"
      - name: Run tests (Behat)
        run: ./bin/behat -fprogress --strict

      - name: Run tests (Behat for PHP 8.0)
        if: matrix.php >= 8.0
        run: ./bin/behat -fprogress --strict --tags=@php8