name: CI

on: [ push ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    matrix:
      php: [ '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: "${{ matrix.php }}"
