name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { php: 7.4, phpunit: 9 }
          - { php: 8.0, phpunit: 10 }
          - { php: 8.1, phpunit: 10 }
          - { php: 8.2, phpunit: 10 }
    steps:
      - uses: actions/checkout@v3
      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: "vendor"
          key: ${{ runner.os }}-${{ matrix.env.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer
        run: composer install -o --no-interaction --no-suggest --prefer-dist

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          coverage_cobertura: "cobertura.xml"
          php_version: "${{ matrix.env.php }}"
          php_extensions: "xdebug"
          version: "${{ matrix.env.phpunit }}"
          configuration: "phpunit.xml"
      - name: "Code Coverage Report"
        if: "matrix.env.php == '8.2'"
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage_cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        if: "matrix.env.php == '8.2' && github.event_name == 'pull_request'"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Behat tests
        uses: php-actions/behat@master
        with:
          php_version: "${{ matrix.env.php }}"
